kafka:
  bootstrapAddress: localhost:9092
message:
  topic:
    name: test
greeting:
  topic:
    name: greeting
filtered:
  topic:
    name: filtered
partitioned:
  topic:
    name: partitioned
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: greeting
          contentType: application/json
        greetings-out:
          destination: greeting
          contentType: application/json